/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://nzek7w3wszew5bql5q6fgnorvq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xww4h5npjjdfzbrv7p3dqgi56q",
    "aws_cognito_identity_pool_id": "us-west-2:a795ec1e-9013-4c76-bc38-9886d997518e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_tG0UbG2eL",
    "aws_user_pools_web_client_id": "n9ea3qo09op6ml1h945vek0qi",
    "oauth": {},
    "aws_user_files_s3_bucket": "reactdemobucketdrew233905-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
